### ISSUE TITLE
vader_popup dependency 

### ISSUE THREAD

**Issue by TomaszCz** [StorybookToolkit/storybook_toolkit#1]
Interesting. I am unable to launch example project.

 ![image](https://github.com/user-attachments/assets/2125afef-71c3-4851-a183-352807d66016)
 
 I just cloned this repo, entered example folder and launched `flutter pub get`
 
 
 I guess you should remove pubspec_overrides.yaml from the repo :) 
 And then it works fine:
 
![image](https://github.com/user-attachments/assets/a5e06088-d19e-43c7-8484-92f09b85c49b)

**Comment by mjablecnik** [comment]
Hello, thank you so much for your issue.
I removed pubspec_overrides.yaml from project and added it into .gitignore.
