### ISSUE TITLE
Theme / Background color of the storybook

### ISSUE THREAD

**Issue by TomaszCz** [StorybookToolkit/storybook_toolkit#3]
If I run your example i cannot get rid of purple'ish background color for knob side menu and for stories list. It seems it should be trivial but it is not for me. Do you happen to know how can i have everything white? :) I only managed to accomplish white background for each story / widget.

![image](https://github.com/user-attachments/assets/a57c08c7-e229-4a5c-a725-54a552988204)

I used wrapperBuilder which is basically a modified copy what you have in your [example](https://github.com/StorybookToolkit/storybook_toolkit/blob/master/lib/src/storybook.dart#L96)
```dart
Widget customMaterialWrapper(BuildContext context, Widget? child) {
  return MaterialApp(
    theme: ThemeData.light().copyWith(
      scaffoldBackgroundColor: Colors.white,
      canvasColor: Colors.white,
      brightness: Brightness.light,
      primaryColor: Colors.black,
      textTheme: const TextTheme(
        bodyLarge: TextStyle(color: Colors.black),
        bodyMedium: TextStyle(color: Colors.black87),
        titleMedium: TextStyle(color: Colors.black54),
        displayLarge: TextStyle(color: Colors.black),
        labelLarge: TextStyle(color: Colors.white),
      ),
      buttonTheme: const ButtonThemeData(
        buttonColor: Colors.black,
        textTheme: ButtonTextTheme.primary,
      ),
      appBarTheme: const AppBarTheme(
        color: Colors.white,
        titleTextStyle: TextStyle(color: Colors.black),
        iconTheme: IconThemeData(color: Colors.black),
      ),
      dialogTheme: const DialogTheme(
        backgroundColor: Colors.white,
        titleTextStyle: TextStyle(color: Colors.black),
        contentTextStyle: TextStyle(color: Colors.black),
      ),
      sliderTheme: const SliderThemeData(
        activeTrackColor: Colors.black,
        inactiveTrackColor: Colors.grey,
        thumbColor: Colors.black,
      ),
      colorScheme: const ColorScheme(
        surface: Colors.white,
        brightness: Brightness.light,
        primary: Colors.black,
        onPrimary: Colors.white,
        secondary: Colors.black,
        onSecondary: Colors.white,
        error: Colors.red,
        onSurface: Colors.black,
        onError: Colors.white,
      ),
    ),
    darkTheme: ThemeData.dark().copyWith(scaffoldBackgroundColor: Colors.black),
    debugShowCheckedModeBanner: false,
    home: Directionality(
      textDirection: Directionality.of(context),
      child: Scaffold(
        body: Center(
          child: child ?? const SizedBox.shrink(),
        ),
      ),
    ),
  );
}
```

Usage:
``` dart
Storybook(
        canvasColor: Colors.white,   // does not do anything..
        wrapperBuilder: customMaterialWrapper, // affect only each Story, not the knob side menu / list of widgets
        routeWrapperBuilder: // ommited, not relevant for me
        stories: []
         // other fields not relevant 
)
```

**Comment by mjablecnik** [comment]
If you want to change theme or color of whole application so it is not possible right now. (I didn't expect that somebody will need this)
Right now you can change theme only inside your application but not whole storybook app.

**Comment by TomaszCz** [comment]
The interesting part is that original demo was white [demo](https://ookami-kb.github.io/storybook_flutter/#/) - source page [before fork](https://github.com/ookami-kb/storybook_flutter?tab=readme-ov-file)

I guess you would have to add `scaffoldBackgroundColor `[here](https://github.com/StorybookToolkit/storybook_toolkit/blob/master/lib/src/storybook.dart#L29)
and of course expose it as member of Storybook similar like `canvasColor`. Exposing entire theming would be even more cool but it would not be few liners :)

**Comment by mjablecnik** [comment]
Previous demo was white because there was used old Material 2 design I think. But now default design is Material 3. So maybe there are some changes.. 
Now I am sick so I will fix this problem sometimes later but if you know how to fix it, feel free to make PR and I will merge it ;)

**Comment by TomaszCz** [comment]
I know how to solve it :) Can you give me a collaborator permissions so i can push my branch and create PR? :)

![image](https://github.com/user-attachments/assets/cf4d502f-7785-4c15-bcab-a1c8aea4a797)

I made necessary changes to main theme ( left out the material wrapper as this is easily to be changed ). The color is set via `canvasColor` ( I updated example with white ). YOu may or may not notice that i also applied listTileTheme and splashFactory as those are ignored currently.

![image](https://github.com/user-attachments/assets/018854db-178d-44aa-873b-34b9dffab0f4)

**Comment by mjablecnik** [comment]
You can create fork of storybook_toolkit, push changes into your fork and then create PR.
You don't need some additional permissions.

**Comment by TomaszCz** [comment]
Ok, Pr is ready :) Look, i did not care about formatting to prevent unwanted changes.
https://github.com/StorybookToolkit/storybook_toolkit/pull/4

**Comment by mjablecnik** [comment]
@TomaszCz I merged your PR so I close this issue.
